#!/bin/bash

#SBATCH --job-name=test6
#SBATCH -p free
#SBATCH --nodes=1
#SBATCH --ntasks=1           ## ask for 1 CPU 
#SBATCH --mem-per-cpu=1G     ## ask for 1Gb memory per CPU 
#SBATCH --error=%A-%x.err
#SBATCH --out=%A-%x.out

currenthost=`hostname`
echo "This job was run on $currenthost "

module load anaconda/2020.07
. ~/.myconda-2020.07
conda info
conda list envs
echo "PATH is $PATH"
echo "SLURM_JOBID = $SLURM_JOBID"
