#!/bin/bash

#SBATCH --job-name=test10
#SBATCH -p free
#SBATCH --nodes=1
#SBATCH --ntasks=1           ## ask for 1 CPU 
#SBATCH --mem-per-cpu=1G     ## ask for 1Gb memory per CPU 
#SBATCH -t 00:02:00          ## time limit 2 min
#SBATCH --qos=low
#SBATCH --error=%A-%x.err
#SBATCH --requeue
#SBATCH --out=%A-%x.out

echo "Starting at `date`"
echo "Running on hosts: $SLURM_NODELIST"
echo "Running on hosts: $SLURM_JOB_NODELIST"
echo "Running on $SLURM_NNODES nodes."
echo "Running on $SLURM_NPROCS processors."
echo "Current working directory is `pwd`"
echo "Running a dependency test"

sleep 20
