#!/bin/bash

#SBATCH --job-name=test9
#SBATCH -p free
#SBATCH --nodes=1
#SBATCH --ntasks=1           ## ask for 1 CPU 
#SBATCH --mem-per-cpu=1G     ## ask for 1Gb memory per CPU 
#SBATCH -t 00:02:00          ## time limit 2 min
#SBATCH --array=1-4  
#SBATCH --qos=low
#SBATCH --error=%A-%x-%a.err
#SBATCH --out=%A-%x-%a.out

#Set the number of runs that each SLURM task should do
PER_TASK=1000

# Calculate the starting and ending values for this task based
# on the SLURM task ID  and the number of runs per task.
START_NUM=$(( ($SLURM_ARRAY_TASK_ID - 1) * $PER_TASK + 1 ))
END_NUM=$(( $SLURM_ARRAY_TASK_ID * $PER_TASK ))

# Print the task and run range
echo "Task $SLURM_ARRAY_TASK_ID: for runs $START_NUM to $END_NUM"

# Run the loop of runs for this task.
for (( run=$START_NUM; run<=END_NUM; run++ )); do
  echo "SLURM task $SLURM_ARRAY_TASK_ID, run number $run"
  #do your commands here
done

