#!/bin/bash

#SBATCH --job-name=test12
#SBATCH -p free
#SBATCH --nodes=1
#SBATCH --ntasks=1           ## (-n) number of processes to be launched
#SBATCH --cpus-per-task=1
#SBATCH --mem-per-cpu=2G     ## RAM per CPU 
#SBATCH --qos=low
#SBATCH --error=%A-%x.err
#SBATCH --out=%A-%x.out

currenthost=`hostname`
echo "This job was run on $currenthost "

# Run command that will try to run  more memory than requeted  
if [ -f /usr/bin/stress ] ; then
    STRESS=/usr/bin/stress
else
    STRESS=/usr/bin/stress-ng
fi

echo "Running $STRESS --vm-bytes 4G --vm-keep -m 1"
$STRESS --vm-bytes 4G --vm-keep -m 1

