#!/bin/bash

#SBATCH --job-name=test1
#SBATCH -p free
#SBATCH --nodes=1
#SBATCH --mem=5G
#SBATCH --cpus-per-task=2
#SBATCH --error=%A-%x.err
#SBATCH --out=%A-%x.out

currenthost=`hostname`
echo "This job was run on $currenthost "

module load samtools/1.10
module load anaconda/2021.11
module load fastqc/0.11.9
module list

total=`find /opt/rcic/Modules/modulefiles -type f | wc -l`
echo "Installed modules: $total"

